---
- name: Skip Morpheus agent installation
  dpkg_selections:
      name: "morpheus-vm-node"
      selection: hold

- name: Update all packages for Debian OS family
  apt:
    name: "*"
    state: latest
    # exclude: morpheus-vm-node
#   upgrade: dist 
    update_cache: yes
    only_upgrade: yes
  register: DpkgUpdate_status