---
- name: Test async with Morpheus Ansible
  hosts: all
  gather_facts: false

  tasks:

    - name: Long running task
      ansible.builtin.shell:
        cmd: sleep 60
      async: 120
      poll: 3
